[pyprland]
include = [
    "~/.config/hypr/pyprland.d",
]
plugins = [
    "toggle_special",
    "lost_windows",
    "toggle_special",
    "shift_monitors",
    "toggle_dpms",
    "magnify",
    "expose",
    "shift_monitors",
    "workspaces_follow_focus",
    "fetch_client_menu",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = true

[gbar]
monitors = [
    "DP-3",
    "HDMI-A-1",
]
